/**
 * Dolch 220 high-frequency words (public-domain lists) plus original
 * child sentences. Do not copy competitor worksheets.
 */
export const LISTS = [
  {
    id: 'pre-primer',
    title: 'Pre-Primer',
    grade: 'Pre-K',
    words: [
      ['a', 'I see a red ball.'],
      ['and', 'Mom and Dad sit.'],
      ['away', 'The bus went away.'],
      ['big', 'The dog is big.'],
      ['blue', 'The sky is blue.'],
      ['can', 'I can hop.'],
      ['come', 'Come here now.'],
      ['down', 'Sit down please.'],
      ['find', 'Find the hat.'],
      ['for', 'This gift is for you.'],
      ['funny', 'The clown is funny.'],
      ['go', 'We go home.'],
      ['help', 'Help me please.'],
      ['here', 'Come here Sam.'],
      ['I', 'I can run.'],
      ['in', 'The cat is in the box.'],
      ['is', 'The sun is hot.'],
      ['it', 'It is a bug.'],
      ['jump', 'Jump up high.'],
      ['little', 'The little ant hid.'],
      ['look', 'Look at the moon.'],
      ['make', 'Make a cake.'],
      ['me', 'Come with me.'],
      ['my', 'This is my book.'],
      ['not', 'I am not sad.'],
      ['one', 'I have one fish.'],
      ['play', 'We play ball.'],
      ['red', 'The apple is red.'],
      ['run', 'Run to the tree.'],
      ['said', 'She said hello.'],
      ['see', 'I see you.'],
      ['the', 'The frog hops.'],
      ['three', 'I see three bees.'],
      ['to', 'We go to school.'],
      ['two', 'I have two socks.'],
      ['up', 'Look up high.'],
      ['we', 'We can sing.'],
      ['where', 'Where is the cat?'],
      ['yellow', 'The sun is yellow.'],
      ['you', 'I see you smile.'],
    ],
  },
  {
    id: 'primer',
    title: 'Primer',
    grade: 'Kindergarten',
    words: [
      ['all', 'We all sat down.'],
      ['am', 'I am six.'],
      ['are', 'We are here.'],
      ['at', 'Look at the bird.'],
      ['ate', 'I ate a pear.'],
      ['be', 'Be kind.'],
      ['black', 'The cat is black.'],
      ['brown', 'The dog is brown.'],
      ['but', 'I ran but I fell.'],
      ['came', 'A bus came by.'],
      ['did', 'I did my job.'],
      ['do', 'Do your best.'],
      ['eat', 'I eat an apple.'],
      ['four', 'I see four cups.'],
      ['get', 'Get the ball.'],
      ['good', 'You did a good job.'],
      ['have', 'I have a kite.'],
      ['he', 'He can jump.'],
      ['into', 'Hop into bed.'],
      ['like', 'I like milk.'],
      ['must', 'We must rest.'],
      ['new', 'I have a new hat.'],
      ['no', 'No thank you.'],
      ['now', 'Come now.'],
      ['on', 'The book is on the desk.'],
      ['our', 'This is our home.'],
      ['out', 'We went out.'],
      ['please', 'Please sit down.'],
      ['pretty', 'The flower is pretty.'],
      ['ran', 'The pup ran fast.'],
      ['ride', 'Ride the bike.'],
      ['saw', 'I saw a deer.'],
      ['say', 'Say your name.'],
      ['she', 'She can hop.'],
      ['so', 'I am so glad.'],
      ['soon', 'We will eat soon.'],
      ['that', 'I like that song.'],
      ['there', 'Put it there.'],
      ['they', 'They can play.'],
      ['this', 'This is fun.'],
      ['too', 'I can hop too.'],
      ['under', 'The cat hid under the bed.'],
      ['want', 'I want a hug.'],
      ['was', 'The sky was pink.'],
      ['well', 'I feel well.'],
      ['went', 'We went home.'],
      ['what', 'What is that?'],
      ['white', 'The snow is white.'],
      ['who', 'Who is it?'],
      ['will', 'I will help.'],
      ['with', 'Come with me.'],
      ['yes', 'Yes I can.'],
    ],
  },
  {
    id: 'grade-1',
    title: 'Grade 1',
    grade: 'First grade',
    words: [
      ['after', 'We rest after lunch.'],
      ['again', 'Sing it again.'],
      ['an', 'I ate an egg.'],
      ['any', 'Do you want any milk?'],
      ['as', 'I am as tall as you.'],
      ['ask', 'Ask for help.'],
      ['by', 'Sit by me.'],
      ['could', 'I could hop far.'],
      ['every', 'Every bird can sing.'],
      ['fly', 'Birds fly high.'],
      ['from', 'A gift from Mom.'],
      ['give', 'Give me a hand.'],
      ['giving', 'She is giving a gift.'],
      ['had', 'I had a nap.'],
      ['has', 'He has a hat.'],
      ['her', 'This is her book.'],
      ['him', 'I see him.'],
      ['his', 'This is his cup.'],
      ['how', 'How are you?'],
      ['just', 'I just sat down.'],
      ['know', 'I know that song.'],
      ['let', 'Let me help.'],
      ['live', 'We live here.'],
      ['may', 'You may sit.'],
      ['of', 'A cup of milk.'],
      ['old', 'The tree is old.'],
      ['once', 'Once I saw a fox.'],
      ['open', 'Open the box.'],
      ['over', 'The bird flew over us.'],
      ['put', 'Put the book down.'],
      ['round', 'The ball is round.'],
      ['some', 'I want some grapes.'],
      ['stop', 'Stop at the sign.'],
      ['take', 'Take my hand.'],
      ['thank', 'Thank you Dad.'],
      ['them', 'I see them.'],
      ['then', 'Eat then rest.'],
      ['think', 'I think it is fun.'],
      ['walk', 'Walk with me.'],
      ['were', 'We were glad.'],
      ['when', 'When can we play?'],
    ],
  },
  {
    id: 'grade-2',
    title: 'Grade 2',
    grade: 'Second grade',
    words: [
      ['always', 'I always try.'],
      ['around', 'Look around you.'],
      ['because', 'I sat because I was tired.'],
      ['been', 'I have been kind.'],
      ['before', 'Wash before lunch.'],
      ['best', 'Do your best.'],
      ['both', 'Both cats sat.'],
      ['buy', 'We buy milk.'],
      ['call', 'Call my name.'],
      ['cold', 'The wind is cold.'],
      ['does', 'She does her work.'],
      ['dont', 'Do not run in the hall.'],
      ['fast', 'The pup is fast.'],
      ['first', 'I go first.'],
      ['five', 'I see five ducks.'],
      ['found', 'I found my hat.'],
      ['gave', 'Mom gave me a hug.'],
      ['goes', 'The bus goes now.'],
      ['green', 'The grass is green.'],
      ['its', 'The dog wagged its tail.'],
      ['made', 'I made a card.'],
      ['many', 'I see many stars.'],
      ['off', 'Take off the hat.'],
      ['or', 'Red or blue?'],
      ['pull', 'Pull the door.'],
      ['read', 'I read a book.'],
      ['right', 'Turn right.'],
      ['sing', 'We sing a song.'],
      ['sit', 'Sit with me.'],
      ['sleep', 'I sleep at night.'],
      ['tell', 'Tell me a tale.'],
      ['their', 'This is their home.'],
      ['these', 'These are my shoes.'],
      ['those', 'Those birds can fly.'],
      ['upon', 'Once upon a time.'],
      ['us', 'Come with us.'],
      ['use', 'Use a pencil.'],
      ['very', 'I am very glad.'],
      ['wash', 'Wash your hands.'],
      ['which', 'Which hat is mine?'],
      ['why', 'Why is the sky blue?'],
      ['wish', 'I wish I could fly.'],
      ['work', 'I work hard.'],
      ['would', 'I would like a pear.'],
      ['write', 'Write your name.'],
      ['your', 'This is your book.'],
    ],
  },
  {
    id: 'grade-3',
    title: 'Grade 3',
    grade: 'Third grade',
    words: [
      ['about', 'Tell me about your day.'],
      ['better', 'I feel better now.'],
      ['bring', 'Bring your book.'],
      ['carry', 'I can carry the bag.'],
      ['clean', 'Keep your desk clean.'],
      ['cut', 'Cut the paper.'],
      ['done', 'I am done.'],
      ['draw', 'Draw a tree.'],
      ['drink', 'Drink your water.'],
      ['eight', 'I see eight bees.'],
      ['fall', 'Leaves fall in fall.'],
      ['far', 'The hill is far.'],
      ['full', 'The cup is full.'],
      ['got', 'I got a letter.'],
      ['grow', 'Plants grow in sun.'],
      ['hold', 'Hold my hand.'],
      ['hot', 'The soup is hot.'],
      ['hurt', 'My knee is hurt.'],
      ['if', 'If I can I will.'],
      ['keep', 'Keep trying.'],
      ['kind', 'Be kind to all.'],
      ['laugh', 'We laugh a lot.'],
      ['light', 'The light is on.'],
      ['long', 'The path is long.'],
      ['much', 'Thank you very much.'],
      ['myself', 'I can do it myself.'],
      ['never', 'Never give up.'],
      ['only', 'I have only one left.'],
      ['own', 'This is my own cup.'],
      ['pick', 'Pick a flower.'],
      ['seven', 'I see seven fish.'],
      ['shall', 'We shall rest.'],
      ['show', 'Show me the way.'],
      ['six', 'I have six crayons.'],
      ['small', 'The mouse is small.'],
      ['start', 'Start at the top.'],
      ['ten', 'I can count to ten.'],
      ['today', 'Today we play.'],
      ['together', 'We work together.'],
      ['try', 'Try again.'],
      ['warm', 'The sun is warm.'],
    ],
  },
];

/** Printed form of the Grade 2 contraction (Dolch list uses don't). */
export const PRINT_WORD = {
  dont: "don't",
};

export function printWord(word) {
  return PRINT_WORD[word] ?? word;
}

export function flattenWords() {
  const out = [];
  for (const list of LISTS) {
    list.words.forEach(([word, sentence], index) => {
      out.push({
        word,
        print: printWord(word),
        sentence,
        listId: list.id,
        listTitle: list.title,
        grade: list.grade,
        index: index + 1,
        total: list.words.length,
      });
    });
  }
  return out;
}

export function expectedCounts() {
  return {
    'pre-primer': 40,
    primer: 52,
    'grade-1': 41,
    'grade-2': 46,
    'grade-3': 41,
    all: 220,
  };
}
